version: '3.8'
services:
  RESTapi:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval \"db.adminCommand('ping')\""]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 27018:27017
    volumes:
      - /home/ubuntu/mongo-data:/data/db
  
  app:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - RESTapi
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  mongo-data:
