global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['54.89.54.232:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['54.89.54.232:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['54.89.54.232:9100']
